version: '3.8'

services:
  churn-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-prediction-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DEBUG=true
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      # Montage des modèles (lecture seule)
      - ./models_production:/app/models_production:ro
      - ./encoders_churn:/app/encoders_churn:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - churn-network

networks:
  churn-network:
    driver: bridge

# Configuration optionnelle pour monitoring (à activer si besoin)
# services:
#   prometheus:
#     image: prom/prometheus:latest
#     container_name: churn-prometheus
#     ports:
#       - "9090:9090"
#     networks:
#       - churn-network